language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - mvn clean install -B -e -V  --settings settings-travis.xml

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: marcus.maccio@gmail.com
  slack: marmacteam:658FZsYHjVQUVYfWU0Uv0GQF